/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BloodDonor;

/**
 *
 * @author MehediHassanHashemy
 */
import static BloodDonor.AdminI.jTable1;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
        this.setLocationRelativeTo(null);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lebel5 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        lebel7 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        lebel10 = new javax.swing.JLabel();
        lebel4 = new javax.swing.JLabel();
        lebel11 = new javax.swing.JLabel();
        lebel6 = new javax.swing.JLabel();
        lebel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lebel9 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        sq = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        bgroup = new javax.swing.JLabel();
        lastdd = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        lebel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel5.setForeground(new java.awt.Color(255, 255, 255));
        lebel5.setText("National ID:");

        label3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Gender:");

        lebel7.setForeground(new java.awt.Color(255, 255, 255));
        lebel7.setText("Blood Group:");

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Name:");

        label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Username:");

        lebel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel10.setForeground(new java.awt.Color(255, 255, 255));
        lebel10.setText("Contact:");

        lebel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel4.setForeground(new java.awt.Color(255, 255, 255));
        lebel4.setText("Date Of Birth:");

        lebel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel11.setForeground(new java.awt.Color(255, 255, 255));
        lebel11.setText("Email:");

        lebel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel6.setForeground(new java.awt.Color(255, 255, 255));
        lebel6.setText("Address:");

        lebel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel8.setForeground(new java.awt.Color(255, 255, 255));
        lebel8.setText("Last Donation Date:");

        lebel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lebel9.setForeground(new java.awt.Color(255, 255, 255));
        lebel9.setText("Favorite Person:");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));

        gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));

        dob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));

        sq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sq.setForeground(new java.awt.Color(255, 255, 255));

        contact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));

        bgroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bgroup.setForeground(new java.awt.Color(255, 255, 255));

        lastdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastdd.setForeground(new java.awt.Color(255, 255, 255));

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));

        address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));

        name1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        name1.setForeground(new java.awt.Color(204, 204, 255));
        name1.setText("USER PROFILE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lebel6)
                    .addComponent(label1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lebel4)
                        .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lebel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(413, 413, 413))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(78, 78, 78)
                                .addComponent(lebel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lebel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(156, 156, 156)
                                .addComponent(lebel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lebel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lebel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sq, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(name1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lebel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(38, 38, 38)
                                                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lebel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(sq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lebel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lebel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lebel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lebel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lebel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(lastdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lebel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        jMenu1.setText("Edit Information");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        jMenu2.setText("Delete Account");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        jMenu3.setText("Logout");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown

    }//GEN-LAST:event_jPanel1ComponentShown

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        PreparedStatement st;
        ResultSet rs;
        
        String query = "SELECT * FROM `verified_user` WHERE `Username` = ?";
        try {
            st =My_CNX.getConnection().prepareStatement(query);
            
            st.setString(1,LoginUI.user);
            
            rs = st.executeQuery();

            if(rs.next()){
                RegistrationUI2 vu = new RegistrationUI2();
                vu.setVisible(true);
                
                RegistrationUI2.jTextField1.setText(rs.getString(2));
                RegistrationUI2.jTextField2.setText(rs.getString(3));
                if(rs.getString(1).equals("Male")){
                    RegistrationUI2.male.setSelected(true);
                    RegistrationUI2.female.setSelected(false);
                }
                else{
                    RegistrationUI2.female.setSelected(true);
                    RegistrationUI2.male.setSelected(false);
                }
                RegistrationUI2.jTextField3.setText(rs.getString(4));
                RegistrationUI2.jTextField4.setText(rs.getString(5));
                RegistrationUI2.jPasswordField2.setText(rs.getString(6));
                RegistrationUI2.jPasswordField1.setText(rs.getString(6));
                RegistrationUI2.jTextField10.setText(rs.getString(8));
                RegistrationUI2.jTextField9.setText(rs.getString(12));
                if(rs.getString(9).equals("A+")){
                    RegistrationUI2.jComboBox1.setSelectedItem("A+");
                }
                else if(rs.getString(9).equals("A-")){
                    RegistrationUI2.jComboBox1.setSelectedItem("A-");
                }
                else if(rs.getString(9).equals("B+")){
                    RegistrationUI2.jComboBox1.setSelectedItem("B+");
                }
                else if(rs.getString(9).equals("B-")){
                    RegistrationUI2.jComboBox1.setSelectedItem("B-");
                }
                else if(rs.getString(9).equals("O+")){
                    RegistrationUI2.jComboBox1.setSelectedItem("O+");
                }
                else if(rs.getString(9).equals("O-")){
                    RegistrationUI2.jComboBox1.setSelectedItem("O-");
                }
                else if(rs.getString(9).equals("AB+")){
                    RegistrationUI2.jComboBox1.setSelectedItem("AB+");
                }
                else if(rs.getString(9).equals("AB-")){
                    RegistrationUI2.jComboBox1.setSelectedItem("AB-");
                }
                RegistrationUI2.jTextField7.setText(rs.getString(11));
                RegistrationUI2.jTextField6.setText(rs.getString(10));
                RegistrationUI2.jTextField8.setText(rs.getString(7));
                if(rs.getString(13).equals("Yes")){
                    RegistrationUI2.r11.setSelected(true);
                }
                else if(rs.getString(13).equals("No")){
                    RegistrationUI2.r12.setSelected(true);
                }
                else{
                    RegistrationUI2.r11.setSelected(false);
                    RegistrationUI2.r12.setSelected(false);
                }
                
                if(rs.getString(14).equals("Yes")){
                    RegistrationUI2.r21.setSelected(true);
                }
                else if(rs.getString(14).equals("No")){
                    RegistrationUI2.r22.setSelected(true);
                }
                else{
                    RegistrationUI2.r21.setSelected(false);
                    RegistrationUI2.r22.setSelected(false);
                }
                
                if(rs.getString(15).equals("Yes")){
                    RegistrationUI2.r31.setSelected(true);
                }
                else if(rs.getString(15).equals("No")){
                    RegistrationUI2.r32.setSelected(true);
                }
                else{
                    RegistrationUI2.r31.setSelected(false);
                    RegistrationUI2.r32.setSelected(false);
                }
                
                if(rs.getString(16).equals("Yes")){
                    RegistrationUI2.r41.setSelected(true);
                }
                else if(rs.getString(16).equals("No")){
                    RegistrationUI2.r42.setSelected(true);
                }
                else{
                    RegistrationUI2.r41.setSelected(false);
                    RegistrationUI2.r42.setSelected(false);
                }
                
                if(rs.getString(17).equals("Yes")){
                    RegistrationUI2.r51.setSelected(true);
                }
                else if(rs.getString(17).equals("No")){
                    RegistrationUI2.r52.setSelected(true);
                }
                else{
                    RegistrationUI2.r51.setSelected(false);
                    RegistrationUI2.r52.setSelected(false);
                }
                
                if(rs.getString(18).equals("Yes")){
                    RegistrationUI2.r61.setSelected(true);
                }
                else if(rs.getString(18).equals("No")){
                    RegistrationUI2.r62.setSelected(true);
                }
                else{
                    RegistrationUI2.r61.setSelected(false);
                    RegistrationUI2.r62.setSelected(false);
                }
                RegistrationUI2.jTextField14.setText(rs.getString(19));
                RegistrationUI2.jTextField15.setText(rs.getString(20));
                RegistrationUI2.jTextField11.setText(rs.getString(21));
                RegistrationUI2.jTextField12.setText(rs.getString(22));
                RegistrationUI2.jTextField13.setText(rs.getString(23));
                RegistrationUI2.jTextField16.setText(rs.getString(24));
         }
        } catch (SQLException ex) {
            Logger.getLogger(AdminI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        LoginUI a1=new LoginUI();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        DeleteConfirmation dl = new DeleteConfirmation();
        dl.setVisible(true);
        
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel address;
    public static javax.swing.JLabel bgroup;
    public static javax.swing.JLabel contact;
    public static javax.swing.JLabel dob;
    public static javax.swing.JLabel email;
    public static javax.swing.JLabel gender;
    public static javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    public static javax.swing.JLabel lastdd;
    private javax.swing.JLabel lebel10;
    private javax.swing.JLabel lebel11;
    private javax.swing.JLabel lebel4;
    private javax.swing.JLabel lebel5;
    private javax.swing.JLabel lebel6;
    private javax.swing.JLabel lebel7;
    private javax.swing.JLabel lebel8;
    private javax.swing.JLabel lebel9;
    public static javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    public static javax.swing.JLabel sq;
    public static javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
